title: "Adam Alsamadisi"
name: "Adam Alsamadisi"
description: "I'm a teacher who loves meaningful tech integration and meaningful tech-free tinkering! Here to share code, teaching resources, and ceramic creations!"
url: "https://adamalsamadisi.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  
# Theme options
minimal_mistakes_skin: "default"
locale: "en-US"

# Posts listing pagination (used by /posts/)
paginate: 10
paginate_path: "/posts/page:num/"

# Defaults so post cards show read time, excerpt, teaser, etc.
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true          # enable comments per post
      share: false
      author_profile: false
      related: true

# Disqus (replace with your shortname to show the “Please enable JavaScript to view comments” footer stub)
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

# Footer “Follow” links (GitHub + Feed)
author:
  name: "Adam Alsamadisi"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/adamalsamadisi"

# Feed footer link is included by the theme automatically; customize if you host elsewhere:
# atom_feed:
#   path: "https://feeds.yourdomain.com/main"
